### ISSUE TITLE
Implement communication through ViewModels

### ISSUE THREAD

**Issue by yalex1402** [stevenhdz/Project-Technician#1]
Currently, some views are using the models to establish communication but if the project implements view models it will be better because of flexibility.

These are some examples:
`@model IEnumerable<Project_Technician.Models.Contacto>
@model Project_Technician.Models.Contacto
@model IEnumerable<Project_Technician.Models.Employee>`

**Comment by stevenhdz** [comment]
**@model IEnumerable<Project_Technician.Models.Contacto>** 

Solved: **@model IEnumerable<Project_Technician.ViewModels.ContactViewModels>** 
_______________________________
**@model Project_Technician.Models.Contacto** 

Solved: **@model Project_Technician.ViewModels.ContactViewModels** 
_______________________________
**@model IEnumerable<Project_Technician.Models.Employee>**

Fix is incompatible to generate controller, DbContext
